language: python

python:
  - "3.6.3"

install:
  - pip install -r requirements.txt
  - pip install coveralls

env:
  - FLASK_VERSION=1.0.2

before_script:
  - source .env
  - psql -c "CREATE DATABASE development;" -U postgres
  - python api/db_tables.py

script: 
  - py.test --cov tests

after_success:
  - coveralls

cache: pip