language: python

python:
  - "3.6.3"

install:
  - pip install -r requirements.txt
  - pip install coveralls

env:
  - FLASK_VERSION=1.0.2

before_script:
  - source .env
  - psql -c "CREATE DATABASE development;" -U postgres
  - psql -c "CREATE USER carpool WITH PASSWORD 'carpool';" -U postgres
  - psql -c "CREATE TABLE users(
        id serial PRIMARY KEY,
        username varchar UNIQUE,
        firstname varchar,
        lastname varchar,
        email varchar UNIQUE, 
        password varchar);" -U postgres
  - psql -c "CREATE TABLE rides(
            id serial PRIMARY KEY,
            driver varchar UNIQUE NOT NULL,
            destination varchar,
            departure_time varchar, 
            route varchar, 
            extras varchar);" -U postgres
  - psql -c "" -U postgres
  - psql -c "" -U postgres

script: 
  - py.test --cov tests

after_success:
  - coveralls

cache: pip